#!/usr/bin/bash

function search() {
	if GTK_THEME=$THEME yad --entry --text=Search --on-top --ricon=find > ./search.txt
	then
		pacstall -S $(cat ./search.txt) > tmpfile && mv -f tmpfile search.txt
		sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" ./search.txt | tr -dc '[[:print:]]\n' > search-formatted.txt
		sed -i 's/\ .*/ /' ./search-formatted.txt
		sed -i ':a;N;$!ba;s/\n/ /g' ./search-formatted.txt
		#Some how unable to reproduce below with [*]
		sed -i 's/[[*]]//g' ./search-formatted.txt
		sed -i 's/[[]//g' ./search-formatted.txt
		yad --list --print-all --multiple --column="Package Name":TXT $(cat ./search-formatted.txt) --title="package list" --button=Return:0 --buttons-layout=start --center --dclick-action="echo" --multiple --compact --title="Search Results" > /dev/null
		#In case user wants to search again...
		rm -rf "./search-formatted.txt" "./search.txt"
		return 0

	else
		rm -rf "./search-formatted.txt" "./search.txt"
		return 252 #exit code for closed window
fi
}
export -f search

function settings() {
source "/usr/lib/pacstall-gui/settings.sh"
if GTK_THEME=$THEME yad --form --field="Theme (currently is $(echo "$THEME" | sed 's/\<Adwaita\>//g' | sed 's/[:]//g')):":CB 'light!dark' --separator='\n' --field="Keep TMP (currently is $(echo "$KEEPTMP"))":CB 'false!true' > ./setting-noformat.txt
then
	sed -i '/light/s/^/THEME=Adwaita:/' ./setting-noformat.txt || sed -i '/dark/s/^/THEME=Adwaita:/' ./setting-noformat.txt
	sed -i '/false/s/^/KEEPTMP=/' ./setting-noformat.txt || sed -i '/true/s/^/KEEPTMP=/' ./setting-noformat.txt
	mv -f ./setting-noformat.txt "/usr/lib/pacstall-gui/settings.sh"
else
	rm -rf "./setting-noformat.txt"
fi
#in case settings are changed... same for beginning
source "/usr/lib/pacstall-gui/settings.sh"
}
export -f settings

source "/usr/lib/pacstall-gui/settings.sh"

TMP="$(mktemp -d "/tmp/pacstall-gui-XXX")"
cd "$TMP" || exit 1

wget -q "$(cat /usr/share/pacstall/repo/pacstallrepo.txt)/packagelist"
echo "$(awk '{print "0 "$0}' ./packagelist)" > ./packagelist
sed -i ':a;N;$!ba;s/\n/ /g' ./packagelist
cp "/usr/bin/pacstall" ./pacstall-patched
patch ./pacstall-patched /usr/lib/pacstall-gui/disable-root-check.diff > /dev/null

if GTK_THEME=$THEME yad --list --column="Install":CHK --print-all --multiple --column="Package Name":TXT $(cat ./packagelist) --title="package list" --button=Install:0 --buttons-layout=start --center --dclick-action="true" --multiple --button=Search:"bash -c search" --button=Settings:"bash -c settings" > ./install-packages; then

sed -i '/FALSE/d' ./install-packages
sed -i 's/|//g' ./install-packages && sed -i 's/TRUE//g' ./install-packages
sed -i ':a;N;$!ba;s/\n/ /g' ./install-packages

pkexec $TMP/pacstall-patched -PI $(cat $TMP/install-packages) | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | GTK_THEME=$THEME yad --form --field="Detailed view":TXT --text="Installing $(cat $TMP/install-packages)..." --title="Installing $(cat $TMP/install-packages) pacscripts" --scroll --cycle-read --button=Abort/End:1 --text="You can close this window once all pacscripts are installed. You can tell by INFO: Cleaning Up." --on-top --width="300" --height="300"
fi

if [[ "$KEEPTMP" == false ]]
then
rm -rf "$(pwd)"
fi
exit 0
